package com.cmcu.itstudy.enums;

public enum NotificationType {
    POST_LIKED,
    POST_COMMENTED,
    COMMENT_LIKED,
    COMMENT_REPLIED,
    POST_REPORTED,
    POST_HIDDEN,
    POST_DELETED,
    REPORT_DISMISSED,
    CONTRIBUTOR_APPROVED,
    CONTRIBUTOR_REJECTED,
    DOCUMENT_COMMENTED,
    POST_UPVOTED,
    DOCUMENT_PURCHASED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED
}
