package com.cmcu.itstudy.dto.document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MyDocumentQuizItemDto {

    private String quizId;
    private String quizTitle;
    private String description;
    private Long totalQuestions;
    private Integer durationMinutes;
    private Double passScorePercent;
    private Boolean isAutoGenerated;
    private String generationId;
    private String generationStatus;
    private String documentId;
    private String documentTitle;
    private String documentFileName;
    private String documentThumbnailUrl;
    private LocalDateTime createdAt;
}
