package com.cmcu.itstudy.service.contract;

/**
 * Backend-only server-side upload of an already-generated preview
 * artifact to Supabase Storage.
 *
 * <p>This contract is intentionally separate from
 * {@link SupabaseStorageService} because the existing client-driven
 * upload pipeline relies on a short-lived signed {@code token} that
 * the browser PUTs. The Phase&nbsp;O3 worker runs server-side and
 * cannot use that client-driven flow; it must upload the PDF bytes
 * directly with the service-role credentials configured in
 * {@link com.cmcu.itstudy.config.SupabaseProperties}.</p>
 *
 * <p>Implementations MUST:</p>
 * <ul>
 *   <li>never log the service-role key, apikey, Authorization header,
 *       signed URL, or signed token;</li>
 *   <li>never expose the raw Supabase response body that might echo a
 *       signed URL;</li>
 *   <li>enforce a hard upper bound on the byte payload (the caller
 *       verifies the size before calling but the adapter re-checks as
 *       a defense-in-depth);</li>
 *   <li>perform the upload outside any database transaction so the
 *       claim commit and the upload commit never interleave;</li>
 *   <li>retry no network error: HTTP failures map to a typed
 *       retryable or terminal exception that the worker classifier
 *       maps onto the standard {@code RETRY}/{@code DEAD} transitions.</li>
 * </ul>
 *
 * <p>The contract is purposely minimal: it does not accept a
 * {@code rawFilename}, an authenticated user id, or a path fragment
 * supplied by a client. The bucket and path are passed verbatim by
 * the worker because the worker builds them through the deterministic
 * {@code DocumentPreviewPathBuilder} contract.</p>
 */
public interface DocumentPreviewServerUploadService {

    /**
     * Upload the provided PDF bytes to Supabase Storage as the
     * {@code (bucket, path)} object.
     *
     * <p>The call has the following contract:</p>
     * <ul>
     *   <li>the caller (worker) MUST have already validated the PDF
     *       through {@code OfficePdfValidationService};</li>
     *   <li>the bucket and path MUST be server-generated by the
     *       deterministic path builder;</li>
     *   <li>the call MUST NOT be invoked inside a database transaction.</li>
     * </ul>
     *
     * @param bucket      the bucket name (must be a configured private
     *                    preview bucket; never null or blank)
     * @param path        the object path (must be server-generated;
     *                    never null or blank)
     * @param pdfBytes    the canonical PDF bytes (must be non-empty and
     *                    pass the hard size cap; never null)
     * @param contentType the canonical content type to advertise
     *                    (typically {@code application/pdf})
     * @throws com.cmcu.itstudy.handle.SignedUploadTargetFailedException
     *         for any non-recoverable Supabase failure (401/403/5xx,
     *         timeout, network). The internal category and the cause
     *         are logged server-side but never surfaced.
     */
    void uploadPdfPreview(String bucket, String path, byte[] pdfBytes,
                          String contentType);
}
