package com.cmcu.itstudy.service.contract;

import com.cmcu.itstudy.entity.PendingStorageUpload;
import com.cmcu.itstudy.entity.User;
import com.cmcu.itstudy.enums.AllowedDocumentFileType;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Persists {@link PendingStorageUpload} rows for paid uploads.
 *
 * <p>This service never calls Supabase and never accepts a bucket, path,
 * or userId from the request body. All inputs are server-resolved.
 *
 * <p>The orchestrator is the single source of:
 * <ul>
 *   <li>{@code uploadId} — generated exactly once via {@link UUID#randomUUID()}
 *       and reused for the Supabase path, the persisted row, and the
 *       response.</li>
 *   <li>{@code now} (used as {@code createdAt} / {@code updatedAt}) —
 *       computed from the application clock once.</li>
 *   <li>{@code bindExpiresAt} — the StudyIT pending-upload bind deadline
 *       ({@code now + 15 minutes}).</li>
 * </ul>
 *
 * <p>This service is FORBIDDEN to call {@code LocalDateTime.now()} or
 * {@code UUID.randomUUID()} internally. All timestamps and identifiers
 * are supplied by the caller, so timestamps stay consistent across
 * orchestrator / registration service / response / persisted row.
 *
 * <h2>Future pending-operation clock contract</h2>
 * <p>Future pending-upload operations must use the same application
 * clock bean:
 * <ul>
 *   <li>bind pending upload — caller-supplied {@code now}.</li>
 *   <li>claim expired uploads — caller-supplied {@code now}.</li>
 *   <li>mark cleaning — caller-supplied {@code now}.</li>
 *   <li>mark expired — caller-supplied {@code now}.</li>
 *   <li>cleanup scheduling — caller-supplied {@code now} from the
 *       application clock bean.</li>
 * </ul>
 * The orchestrator / caller computes {@code now} from the application
 * clock and passes it to each operation. Implementations never mix
 * {@code LocalDateTime.now()} (JVM default zone) with
 * {@code LocalDateTime.now(Clock.systemUTC())} within the same lifecycle.
 */
public interface PendingUploadRegistrationService {

    /**
     * Create and persist a new {@link PendingStorageUpload} row.
     *
     * @param uploadId         application-assigned UUID (generated by the
     *                         orchestrator)
     * @param user             authenticated backend user
     * @param bucket           private bucket name (resolved from
     *                         {@link com.cmcu.itstudy.config.SupabaseProperties})
     * @param path             server-generated object path
     * @param fileType         canonical file type resolved by the validator
     * @param fileName         original filename (metadata only)
     * @param expectedSizeBytes request-declared size
     * @param now              application-clock instant used for
     *                         {@code createdAt}/{@code updatedAt}; must
     *                         equal {@code bindExpiresAt} minus 15 minutes
     * @param bindExpiresAt    StudyIT pending-upload bind deadline
     *                         ({@code now + 15 minutes})
     * @return persisted entity
     */
    PendingStorageUpload register(
            UUID uploadId,
            User user,
            String bucket,
            String path,
            AllowedDocumentFileType fileType,
            String fileName,
            long expectedSizeBytes,
            LocalDateTime now,
            LocalDateTime bindExpiresAt);
}