package com.cmcu.itstudy.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import lombok.Getter;
import lombok.Setter;

/**
 * Configuration skeleton for Supabase storage integration.
 *
 * <p>This class only binds environment variables to typed fields. It does
 * NOT issue any HTTP request to Supabase and does NOT log the service role
 * key. The actual HTTP client is wired up in a later stage.
 *
 * <p>Expected env / property keys (all optional at this stage):
 * <ul>
 *   <li>supabase.url</li>
 *   <li>supabase.service-role-key</li>
 *   <li>supabase.public-document-bucket</li>
 *   <li>supabase.private-document-bucket</li>
 * </ul>
 *
 * <p>The service role key is read from the server environment only and must
 * never be sent to the frontend or persisted to logs.
 */
@Getter
@Setter
@ConfigurationProperties(prefix = "supabase")
public class SupabaseProperties {

    /** Project URL, e.g. https://xxx.supabase.co */
    private String url;

    /** Service role JWT. Server-side only. Never log. */
    private String serviceRoleKey;

    /** Public bucket name for free / legacy paid documents. */
    private String publicDocumentBucket;

    /** Private bucket name for paid documents. Requires signed URL access. */
    private String privateDocumentBucket;

    /**
     * Private bucket for preview artifacts generated by the
     * Phase&nbsp;O3 worker. When unset, the worker falls back to
     * {@link #privateDocumentBucket} so an operator who has not yet
     * provisioned a dedicated preview bucket still gets a working
     * setup. The fallback is intentional &mdash; the preview bucket
     * is a normal Supabase Storage bucket and does not require a
     * different credential.
     */
    private String privatePreviewBucket;

    /**
     * Resolves the bucket name used for generated PDF previews. When
     * the operator has provisioned a dedicated
     * {@code supabase.private-preview-bucket} we use that; otherwise
     * we fall back to the paid-document bucket so an operator who
     * hasn't provisioned the dedicated bucket still has a working
     * default.
     */
    public String resolvedPrivatePreviewBucket() {
        if (privatePreviewBucket != null && !privatePreviewBucket.isBlank()) {
            return privatePreviewBucket;
        }
        return privateDocumentBucket;
    }
}