package com.cmcu.itstudy.controller;

import com.cmcu.itstudy.dto.autoquiz.AutoQuizSourceResolutionDto;
import com.cmcu.itstudy.handle.PreviewFileTooLargeException;
import com.cmcu.itstudy.handle.SignedUploadTargetFailedException;
import com.cmcu.itstudy.handle.StorageObjectNotFoundException;
import com.cmcu.itstudy.service.contract.AutoQuizSourceAccessService;
import com.cmcu.itstudy.service.contract.SupabaseStorageService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

/**
 * Phase 2E-A: secure source-PDF endpoint for the Auto Quiz pipeline.
 *
 * <h2>Route</h2>
 * <pre>
 *   GET /api/auto-quiz/generations/{generationId}/source
 *   Header: X-Auto-Quiz-Dispatch-Token: (uuid)
 * </pre>
 *
 * <h2>Wire contract</h2>
 * <ul>
 *   <li>Content-Type: application/pdf on success (regardless of
 *       whether the original file is a PDF or a DOC/DOCX; DOC/DOCX
 *       is resolved through the FULL preview PDF generated by the
 *       async LibreOffice pipeline).</li>
 *   <li>Content-Disposition: inline; filename="auto-quiz-source.pdf"
 *       so n8n (and humans debugging) can persist the bytes with a
 *       stable name.</li>
 *   <li>X-Auto-Quiz-Source-Kind: PDF_ORIGINAL or DOC_PREVIEW_FULL so
 *       the dispatch worker can record the source origin in its own
 *       audit log. No internal storage details are exposed.</li>
 *   <li>On failure: 403 Forbidden with the safe ApiResponse.failure
 *       envelope produced by GlobalExceptionHandler for
 *       AutoQuizSourceAccessDeniedException. Bucket, path, expected
 *       token, generationId, and documentFileId are NEVER echoed.</li>
 * </ul>
 *
 * <h2>Authentication</h2>
 * <p>This endpoint is deliberately JWT-less: it relies on the per-row
 * dispatchToken lease that the dispatcher wrote into
 * QuizGeneration.dispatchToken during the Phase 2D claim
 * transaction. The token is opaque, single-use-while-valid, and
 * rotated by the dispatcher on every retry.</p>
 *
 * <h2>Safety</h2>
 * <ul>
 *   <li>The endpoint is added to SecurityConfig.permitAll() with the
 *       EXACT matcher /api/auto-quiz/generations/STAR/source; no
 *       wildcard prefix is opened.</li>
 *   <li>Bucket / path are resolved server-side from the
 *       QuizGeneration row's bound DocumentFile and (for DOC/DOCX)
 *       its most recent READY FULL DocumentPreviewArtifact. The
 *       caller cannot influence which object is downloaded.</li>
 *   <li>Bytes are streamed through
 *       SupabaseStorageService.downloadPrivateObject. The endpoint
 *       never redirects to a Supabase object URL and never emits a
 *       signed URL.</li>
 *   <li>The endpoint is READ-ONLY with respect to the generation
 *       lifecycle: it does NOT change attempts, dispatchToken,
 *       status, lastError, or any retry-related field.</li>
 * </ul>
 */
@RestController
@RequestMapping("/api/auto-quiz")
public class AutoQuizSourceController {

    private static final Logger log =
            LoggerFactory.getLogger(AutoQuizSourceController.class);

    /**
     * Header carrying the dispatch lease token. n8n MUST echo the
     * dispatchToken value it received in the dispatch payload.
     */
    public static final String HEADER_DISPATCH_TOKEN =
            "X-Auto-Quiz-Dispatch-Token";

    /**
     * Operational header that records which kind of source bytes
     * were served. Safe to expose to n8n; carries no storage
     * metadata.
     */
    public static final String HEADER_SOURCE_KIND =
            "X-Auto-Quiz-Source-Kind";

    /**
     * Stable filename used in Content-Disposition. The bytes are
     * always a PDF regardless of the original file kind.
     */
    private static final String DOWNLOAD_FILENAME = "auto-quiz-source.pdf";

    private final AutoQuizSourceAccessService sourceAccessService;
    private final SupabaseStorageService storageService;

    public AutoQuizSourceController(
            AutoQuizSourceAccessService sourceAccessService,
            SupabaseStorageService storageService) {
        this.sourceAccessService = sourceAccessService;
        this.storageService = storageService;
    }

    /**
     * Stream the AI-readable PDF source for the given generation.
     *
     * <p>The path carries only the generation id; the DocumentFile
     * binding is taken from the generation row itself so the caller
     * cannot direct the endpoint at an unrelated file. The dispatch
     * token header binds the request to the in-flight dispatch
     * lease.</p>
     *
     * @param generationId      path-bound generation id
     * @param dispatchTokenRaw  raw header value
     *                          (X-Auto-Quiz-Dispatch-Token); parsed
     *                          as a UUID here so an unparseable value
     *                          is rejected as "missing" rather than
     *                          crashing the handler
     * @return 200 application/pdf on success
     */
    @GetMapping(value = "/generations/{generationId}/source",
            produces = MediaType.APPLICATION_PDF_VALUE)
    public ResponseEntity<byte[]> getGenerationSource(
            @PathVariable("generationId") UUID generationId,
            @RequestHeader(value = HEADER_DISPATCH_TOKEN,
                    required = false) String dispatchTokenRaw) {

        UUID suppliedToken = parseDispatchToken(dispatchTokenRaw);
        // A blank / unparseable token is treated as MISSING_TOKEN by
        // the service. The service also handles null suppliedToken
        // explicitly.
        AutoQuizSourceResolutionDto resolved = sourceAccessService
                .resolveSource(generationId, suppliedToken);

        // Storage IO runs OUTSIDE any database transaction per the
        // SupabaseStorageService contract. The controller never
        // touches the bucket / path strings other than to pass them
        // to downloadPrivateObject and never echoes them in the
        // response or in the log line.
        byte[] pdfBytes = downloadBytes(resolved);

        log.info(
                "Auto Quiz source access served: generationId={} "
                        + "sourceKind={} byteCount={}",
                generationId,
                resolved.sourceKind(),
                pdfBytes != null ? pdfBytes.length : 0);

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_PDF);
        headers.set(HttpHeaders.CONTENT_DISPOSITION,
                "inline; filename=\"" + DOWNLOAD_FILENAME + "\"");
        headers.set(HEADER_SOURCE_KIND, resolved.sourceKind().name());
        return ResponseEntity.ok().headers(headers).body(pdfBytes);
    }

    /**
     * Parse the raw header value into a UUID. null / blank /
     * unparseable values all collapse to null so the service layer
     * can emit a uniform MISSING_TOKEN / TOKEN_MISMATCH response.
     */
    private static UUID parseDispatchToken(String raw) {
        if (raw == null) {
            return null;
        }
        String trimmed = raw.trim();
        if (trimmed.isEmpty()) {
            return null;
        }
        try {
            return UUID.fromString(trimmed);
        } catch (IllegalArgumentException ex) {
            return null;
        }
    }

    /**
     * Thin wrapper over SupabaseStorageService.downloadPrivateObject
     * so the controller logic stays at one abstraction level.
     *
     * <p>Errors are translated into the existing safe exceptions so
     * GlobalExceptionHandler can emit the project's standard
     * ApiResponse.failure envelope.</p>
     */
    private byte[] downloadBytes(AutoQuizSourceResolutionDto resolved) {
        try {
            return storageService.downloadPrivateObject(
                    resolved.bucket(), resolved.path());
        } catch (StorageObjectNotFoundException notFound) {
            // The generation row claimed the source is at this
            // bucket/path but the storage object is missing. We do
            // NOT leak the bucket/path; the safe envelope simply
            // says the source is unavailable.
            log.warn(
                    "Auto Quiz source access: storage object missing "
                            + "for sourceKind={}",
                    resolved.sourceKind());
            throw new SignedUploadTargetFailedException(
                    "Source storage object is unavailable");
        } catch (SignedUploadTargetFailedException transport) {
            // Already a safe exception; let the global handler emit
            // its standard envelope.
            log.warn(
                    "Auto Quiz source access: storage transport "
                            + "failure for sourceKind={}",
                    resolved.sourceKind());
            throw transport;
        } catch (PreviewFileTooLargeException tooLarge) {
            log.warn(
                    "Auto Quiz source access: source exceeds 25MB cap "
                            + "for sourceKind={}",
                    resolved.sourceKind());
            throw tooLarge;
        }
    }
}
