package com.cmcu.itstudy.dto.autoquiz;

/**
 * Phase 2E-A: server-resolved source descriptor for the Auto Quiz
 * secure-source endpoint.
 *
 * <p>This record is the boundary object returned by
 * AutoQuizSourceAccessService AFTER all access checks have passed
 * and the storage source has been resolved. The bucket / path here
 * are intended for INTERNAL use only; they MUST NOT be echoed back
 * to the n8n caller in headers, body, or logs.</p>
 *
 * <h2>Field semantics</h2>
 * <ul>
 *   <li>bucket / path: the Supabase private bucket and object path.
 *       For PDF originals these point to
 *       DocumentFile.storageBucket / DocumentFile.storagePath. For
 *       DOC/DOCX they point to the most recent READY FULL
 *       DocumentPreviewArtifact's storageBucket / storagePath.</li>
 *   <li>fileExtension: the canonical lowercase extension of the
 *       resolved source (always "pdf" for both PDF originals and
 *       DOC/DOCX FULL preview artifacts).</li>
 *   <li>contentType: the MIME type the controller will set on the
 *       response (always "application/pdf").</li>
 *   <li>sourceKind: describes the origin of the bytes so callers
 *       (e.g. tests) can distinguish "PDF original" from "FULL
 *       preview PDF (DOC/DOCX)".</li>
 * </ul>
 */
public record AutoQuizSourceResolutionDto(
        String bucket,
        String path,
        String fileExtension,
        String contentType,
        SourceKind sourceKind) {

    /**
     * Origin of the resolved source bytes.
     */
    public enum SourceKind {
        /** Bytes come from the original PDF DocumentFile. */
        PDF_ORIGINAL,
        /** Bytes come from the most recent READY FULL preview artifact
         *  generated by the LibreOffice pipeline for a DOC/DOCX
         *  document. No reconversion happens at request time. */
        DOC_PREVIEW_FULL
    }

    /**
     * Convenience: the only content type the controller is allowed
     * to ship from this endpoint.
     */
    public static final String CONTENT_TYPE_PDF = "application/pdf";

    /**
     * Convenience: the canonical lowercase extension of every
     * resolved source.
     */
    public static final String EXTENSION_PDF = "pdf";
}
